name: Build APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # البيئة المستقرة تماماً لبلدوزر القديم
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev tk-dev libgdbm-compat-dev libreoffice-dev libxml2-dev libxslt1-dev
        pip install --upgrade pip
        pip install "buildozer<1.6.0" cython virtualenv

    - name: Build with Buildozer
      run: |
        # تعديل الإعدادات أوتوماتيكياً لقبول الشروط
        sed -i 's/android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec || true
        buildozer android debug
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Zard-Calculator-APK
        path: bin/*.apk
        
