name: Build APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Force Settings in Spec
      run: |
        # تفعيل الموافقة التلقائية على التراخيص جوه الملف
        sed -i 's/android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
        sed -i 's/# android.accept_sdk_license = True/android.accept_sdk_license = True/g' buildozer.spec
        # إرجاع المتطلبات للوضع الافتراضي المستقر لمنع التعارض
        sed -i 's/requirements = .*/requirements = python3,kivy/g' buildozer.spec

    - name: Build APK with Official Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        buildozer_version: stable

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Calculator-APK
        path: bin/*.apk
        
